networks:
  kafka-network:
    name: kafka-network
    external: true
    driver: bridge


services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - kafka-network
    restart: always

  mqtt-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-consumer
    command:  "watchmedo auto-restart --directory=/app/src -- python -m src.main"
    networks:
      - kafka-network
    volumes:
      - ./:/app
    environment:
      - MQTT_BROKER=mqtt-broker
      - KAFKA_BROKER=kafka:29092
    restart: always
