networks:
  kafka-network:
    name: kafka-network
    external: true
    driver: bridge


services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - kafka-network
    restart: always

  mqtt-consumer:
    build:
      context: ./mqtt-consumer
      dockerfile: Dockerfile
    container_name: mqtt-consumer
    command:  "watchmedo auto-restart --directory=/app/src -- python -m src.main"
    networks:
      - kafka-network
    volumes:
      - ./mqtt-consumer/src:/app/src
    environment:
      - MQTT_BROKER=mqtt-broker
      - KAFKA_BROKER=kafka:29092
      - MQTT_PORT=1883
      - MQTT_TOPIC=stadtwerke/#
      - KAFKA_PRODUCER_TOPIC=raw-messages
      - TRACER_OTLP_ENDPOINT=http://tempo:4317
    restart: always
