networks:
  kafka-network:
    name: kafka-network
    external: true
    driver: bridge


services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - kafka-network
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"