networks:
  kafka-network:
    name: kafka-network
    external: true
    driver: bridge


services:
  influxdb:
    image: influxdb:2.7 
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${DOCKER_INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_TOKEN: ${DOCKER_INFLUXDB_INIT_TOKEN}
    networks:
      - kafka-network
    volumes:
      - influxdb-data:/var/lib/influxdb2  
    restart: always
  persistence-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persistence-service
    command: "watchmedo auto-restart --directory=/app/src -- python -m src.main"
    volumes:
      - ./:/app
    networks:
      - kafka-network
    environment:
      - KAFKA_BROKER=kafka:29092
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_TOKEN}
    restart: always  


volumes:
  influxdb-data:
    driver: local
