version: '3.7'

networks:
  kafka-network:
    name: kafka-network
    external: true
    driver: bridge

services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3100:3100"  # Tempo HTTP Endpoint
      - "4317:4317"  # OTLP
    volumes:
      - ./tempo.yml:/etc/tempo/tempo.yml 
    networks:
      - kafka-network
    command:
      - --config.file=/etc/tempo/tempo.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - kafka-network
    depends_on:
      - tempo

volumes:
  grafana-storage:
    driver: local
