networks:
  kafka-network:
    name: kafka-network
    external: true
    driver: bridge

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - kafka-network
    ports:
      - "16686:16686" 
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    command:
      - "--query.ui-config=/etc/jaeger/jaeger-ui.json"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      METRICS_STORAGE_TYPE: "prometheus"
      PROMETHEUS_SERVER_URL: "http://prometheus:9090"
      PROMETHEUS_QUERY_NORMALIZE_CALLS: "true"
      PROMETHEUS_QUERY_NORMALIZE_DURATION: "true"
      QUERY_MONITOR_MENU_ENABLED: "true"
    volumes:
      - ./jaeger-ui.json:/etc/jaeger/jaeger-ui.json