networks:
  kafka-network:
    name: kafka-network
    external: true
    driver: bridge


services:
  mqtt-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-consumer
    command:  "watchmedo auto-restart --directory=/app/src -- python -m src.main"
    networks:
      - kafka-network
    volumes:
      - ./:/app
    environment:
      - MQTT_BROKER=mqtt-broker
      - KAFKA_BROKER=kafka:29092
      - TRACER_OTLP_ENDPOINT=http://tempo:4317
    restart: always
